***** NumPy Basics... *****

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b=np.array([[9,8,7],[6,5,4]])
print(b)

[[9 8 7]
 [6 5 4]]


In [4]:
#Get dimension
b.ndim

2

In [5]:
#Get shape
a.shape

(3,)

In [6]:
b.shape

(2, 3)

In [7]:
#Get type
a.dtype

dtype('int32')

In [8]:
#Get size
a.itemsize

4

In [9]:
#Get no of elements
a.size

3

In [10]:
#Get total size
a.size * a.itemsize

12

In [11]:
#Get total size
a.nbytes

12

***** Accessing/Changing specific elements, rows, columns... *****

In [12]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
a.shape

(2, 7)

In [14]:
#Get a specific element [r,c]
a[1,5]

13

In [15]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [17]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [18]:
#Changing element
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [19]:
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


***** 3-D Example...  *****

In [20]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
#Get specific element (work outside in)
b[0,1,1]

4

In [22]:
#I want 6
b[1,0,1]

6

In [23]:
#I want 3
b[0,1,0]

3

In [24]:
#I want 7
b[1,1,0]

7

In [25]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [26]:
#Replace
b[:,1,:]=[[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

***** Initializing Different Types of Arrays... *****

In [27]:
#ALL 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [28]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [30]:
np.zeros((3,2,5,))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [31]:
#ALL 1s matrix
np.ones((5,1,3))

array([[[1., 1., 1.]],

       [[1., 1., 1.]],

       [[1., 1., 1.]],

       [[1., 1., 1.]],

       [[1., 1., 1.]]])

In [32]:
#Any other number
np.full((3,4),27)

array([[27, 27, 27, 27],
       [27, 27, 27, 27],
       [27, 27, 27, 27]])

In [33]:
#Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [34]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.19390127, 0.07500452],
       [0.79168099, 0.72074643],
       [0.53192404, 0.49245287],
       [0.635616  , 0.69155261]])

In [37]:
#Random integer values
np.random.randint(7,75, size=(3,3))

array([[55,  7, 56],
       [48,  8, 51],
       [69,  7, 17]])

In [38]:
#Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
#Repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,4,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [51]:
#      1  1  1  1  1
#      1  0  0  0  1
#      1  0  9  0  1
#      1  0  0  0  1
#      1  1  1  1  1

output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
print(z)

z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


BE CAREFUL WHILE COPYING ARRAYS!!!!!

In [53]:
a = np.array([1,2,3])
b=a
b[0] = 100
print(b)
print(a)    #Value of a is also changed

[100   2   3]
[100   2   3]


In [54]:
#To prevent the change in value of a, we use .copy()
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


***** Mathematics *****

In [55]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [56]:
a+2

array([3, 4, 5, 6])

In [57]:
a-2

array([-1,  0,  1,  2])

In [58]:
a*2

array([2, 4, 6, 8])

In [59]:
b=np.array([2,5,3,1])
a+b

array([3, 7, 6, 5])

In [61]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

***** Linear Algebra *****

In [65]:
#Multiplying matrices
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [66]:
#Finding determinant
c = np.identity(3)
np.linalg.det(c)

1.0

***** Statistics *****

In [67]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
np.min(stats)

1

In [69]:
np.max(stats)

6

In [70]:
np.sum(stats)

21

***** Reorganizing Arrays *****

In [72]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [76]:
#Vertically stacking matrices
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2]))
print(np.vstack([v1,v2,v2,v1]))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [1 2 3 4]]


In [77]:
#Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

***** Miscellaneous *****

Load Data from File

In [ ]:
filedata = np.genfromtxt('file.txt', delimiter=',')

Boolean Masking and Advanced Indexing

In [ ]:
filedata > 50

In [ ]:
filedata[filedata>50]